### ISSUE TITLE
Tracking: rust optimizer

### ISSUE THREAD

**Issue by st1page** [singularity-data/risingwave#109]
When you want to begin a task, please create a corresponding issue, assign yourself and add link here.
### Expression utility functions
- [x] impl `get_col_refs` used by optimizer.  #163 
- [x] #106 
- [x] #107 
### Logical Nodes
the logical Node should have a friendly create function for the binder/planner
the `ToBatch ` `ToStream` and `ToDistributedBatch` can be todo!()
- [x] #108 
- [x] `LogicalScan` #81 
- [x] `LogicalInsert`
- [x] create function of the `LogicalAgg`
- [x] `LogicalJoin` schema derive
- [x] create function of `JoinPredicate`
### Batch Nodes
also should implement `ToBatch` and `ToDistributedBatch` for the Logical node
- [x] `BatchValues`
- [x] `BatchLimit` #167 
- [x] `BatchTopN`
- [x] `BatchFilter`
- [x] `BatchInsert`
- [ ] `BatchSortAgg`
- [x] `BatchHashAgg`
- [ ] `BatchSortMergeJoin` the `derive_order` and `right_required_order_from_left_order` function
### Stream Primary Key Derive 
We should add the trait for Primary Key Derive framework before implement the following Stream Nodes
### Stream Nodes
should implement the StreamPlanNode and the correspond function in `ToStream`
- [x] `StreamTopN`
- [x] https://github.com/singularity-data/risingwave-dev/issues/930
- [x] `StreamMaterialize`
- [x] `StreamFilter`
- [x] `StreamStatefulSimpleAgg`
- [x] `StreamHashAgg`
- [x] `StreamJoin`

## Optimization
they will not will not affect correctness with the default implementation of the traits
### Column Pruning
we have a `ColPrunable` trait on LogicalNode, every node should override its `prune_col` function.
- [x] https://github.com/singularity-data/risingwave-dev/issues/640
### Filter Push Down
we should implement the filter push down rules and use them in `HeuristicOptimizer`
- [x] https://github.com/singularity-data/risingwave-dev/issues/842
### physical properties
we have traits `WithOrder` and `WithDistribution`, the Batch and Stream Node should return there output's physical properties correctly to avoid the unnecessary Exchange or OrderBy operator
### Subquery Unnesting
- [x] https://github.com/singularity-data/risingwave/issues/1343
- [x] unnesting

## temporarily will not do
- the physical properties required inputs or passThough function in `trait PlanTreeNode`
- 2-phase Agg
- Limit PushDown
