### ISSUE TITLE
TODO: support config change for assign split in SourceExecutor

### ISSUE THREAD

**Issue by tabVersion** [singularity-data/risingwave#1285]
SourceExecutor will rebuild a ConnectorSource every time receiving an `assign-split` mutation and then turn it into streaming when `next` is called later. 

- [x] impl a unified function to build all kinds of SplitReader in `rust/connector`
- [x] remove `CreateSourceExecutor` from `rust/batch`
- [x] introduce assign-split mutation in stream

Here we introduce a new assumption that assign-split mutation must happen before the first `next` called. Otherwise SourceExecutor will give empty StreamChunk or even panic.
