### ISSUE TITLE
Tracking: stream manager in Meta service

### ISSUE THREAD

**Issue by yezizp2012** [singularity-data/risingwave#188]
This is a tracking issues, recording steps the stream manager need to implement in Meta.
- [x] Interfacing to barrier manager when creating materialized view.
- [x] [record materialized view dependencies to support drop table and materialized view.](https://github.com/singularity-data/risingwave-dev/issues/191)
- [x] materialized view distributed scheduling.
- [x] support search and queriable on fragment/actor, to support failover/scale etc.
