### ISSUE TITLE
meta: support rewrite multi-way join

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1962]
https://github.com/singularity-data/risingwave/blob/main/src/meta/src/stream/rewrite/delta_join.rs

Currently, the rewriter on meta only supports delta join for two ways. We should modify the rewriter to support multi-way joins, generate multi-way join plans, and later modify frontend to generate multi-way join plan.

**Comment by skyzh** [comment]
- [ ] Add `MultiWayDeltaJoin` plan node in proto.
- [ ] Support rewrite of `MultiWayDeltaJoin` plan node.
- [ ] Before fragmenter runs, if `enable_delta_join` is enabled, rewrite `HashJoin` into `MultiWayDeltaJoin` on meta node.

**Comment by skyzh** [comment]
closed in favor of https://github.com/singularity-data/risingwave/issues/2688
