### ISSUE TITLE
Tracking: hummock compaction group

### ISSUE THREAD

**Issue by zwang28** [singularity-data/risingwave#2065]
### static compaction group
- [x] static compaction group: state and MV. https://github.com/singularity-data/risingwave/pull/2952
- [x] compaction group service/client. https://github.com/singularity-data/risingwave/pull/3061
- [x] register operator to compaction group. https://github.com/singularity-data/risingwave/pull/3044
- [x] write path with compaction group.
- [x] read path with compaction group. 
- [ ] Impact of (more) static compaction groups. It should increase compaction concurrency. But it also causes more shared buffer IO and SSTs.

### dynamic compaction group
- [ ] compaction group management: add/remove groups.
- [ ] specify compaction group for states.
- [ ] merge/split

**Comment by zwang28** [comment]
Reopen when again work on it.
