### ISSUE TITLE
Tracking: DataGen connector

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2401]
RFC: #2377 

- [x] #2402
  - integers
  - floats
  - rows-per-second
- [x] #2747
  - fields.#.min
  - fields.#.max
- [ ] Support VARCHAR for DataGen connector
  - fields.#.length
- [ ] Support TIMESTAMP for DataGen connector
  - fields.#.max-past
- [ ] Support sequence kind for DataGen connector
  - fields.#.kind = 'sequence'
  - fields.#.start
  - fields.#.end
  - Note: It's non-trivial for parallelized source.
- [x] #3095
  - This is not supported by FlinkSQL, but will be useful for debugging.
  - (TBD) seed or fields.#.seed
