### ISSUE TITLE
Tracking: Clean compatible code for legacy frontend

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2539]
Affected components (may be incomplete):

- [x] #2570
- [x] #2557 
- [x] Compute Node: CreateSourceExecutor
- [x] #2552
- [x] Meta: Barrier Manager
- [x] Meta: Cluster Manager
- [x] #2553 
- [x] Compute Node: StreamServiceImpl (see also #2260)
- [x] #794 
- [x] #2555
- [x] #2568

-----------

```
$ ag -i 'Java frontend' .
src/stream/src/from_proto/batch_query.rs
61:            // TODO: remove this branch once we deprecate Java frontend.

src/meta/src/cluster/mod.rs
254:                    // TODO: Java frontend doesn't send heartbeat. Remove this line after using Rust

src/meta/src/stream/fragmenter/mod.rs
44:    // TODO: remove this when we deprecate Java frontend.
263:                    // We didn't make `fields` available on Java frontend yet, so we check if schema
350:                // TODO: Remove this when we deprecate Java frontend.

src/meta/src/barrier/recovery.rs
132:        // Attention, using catalog v2 here, it's not compatible with Java frontend.

src/meta/src/stream/stream_manager.rs
63:    /// TODO: remove this when we deprecate Java frontend.

src/meta/src/rpc/service/epoch_service.rs
23:// TODO: remove EpochService when Java frontend deprecated.

src/common/src/types/chrono_wrapper.rs
137:    /// Converted to microsecond timestamps for compatibility with existing Java frontend.
174:    /// Converted to microsecond timestamps for compatibility with existing Java frontend.

src/common/src/types/mod.rs
95:            // TODO(TaoWu): Java frontend still interprets CHAR as a separate type.
96:            // So to run e2e, we may return VARCHAR that mismatches with what Java frontend
97:            // expected. Fix this when Java frontend fully deprecated.

src/batch/src/executor2/stream_scan.rs
23:// TODO: Remove this when Java frontend is completely removed.

src/batch/src/executor2/insert.rs
112:                // Materialize plan is generated by the optimizer with Java frontend, so we

src/batch/src/executor/create_source.rs
22:// TODO: Remove this when Java frontend is completely removed.
```

```
$ ag legacy_frontend .
src/meta/src/stream/stream_manager.rs
64:    pub is_legacy_frontend: bool,
292:            is_legacy_frontend,
323:        if !is_legacy_frontend {

src/meta/src/stream/fragmenter/graph/stream_graph.rs
565:        if ctx.is_legacy_frontend {
598:                    upstream_actor_id: if ctx.is_legacy_frontend {

src/meta/src/stream/fragmenter/mod.rs
45:    is_legacy_frontend: bool,
116:        is_legacy_frontend: bool,
125:            is_legacy_frontend,
351:                current_fragment.is_singleton = self.is_legacy_frontend;

src/meta/src/rpc/service/stream_service.rs
87:            is_legacy_frontend: true,
```

**Comment by skyzh** [comment]
Also meta's create MV v1 (catalog v1) needs to be removed?
