### ISSUE TITLE
Tracking: AggState unused fields cleaning/refactor

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3235]
When doing #3217, I found a lot of previous used structs can be removed. However, Put it into a single PR is too hard for reviewers. Let's track this.

* [x] Remove keyspace
* [x] Remove Extreme Serializer
* [x] Remove Writebatch 
~~* [ ] Remove `pk_indices`~~
* [ ] Remove `flush` on `ManagedState` (?): Now executor owns state table, so it is nature for executor to control the "flush" -- aka commit.
* [x] Remove `get_mem_table()`.
.....

For WriteBatch, cuz current string_agg still using it (though it is not in e2e, ref: #3115 ), so I do not completely remove it. It's still in the interface.

**Comment by BowenXiao1999** [comment]
Most are tracked in #4035 . Add a todo of remove `.flush()`
