### ISSUE TITLE
Tracking: Store a column either in pk or value, but not both

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#3412]
Tracker for development tasks of https://github.com/singularity-data/risingwave/issues/588.

- [x] Implement dedup pk encoding for cell based table iter https://github.com/singularity-data/risingwave/pull/2957
- [x] Use for row seq scan executor reads https://github.com/singularity-data/risingwave/pull/2957
- [x] Use for batch query executor reads https://github.com/singularity-data/risingwave/pull/3060
- [x] Implement dedup pk serialization for relational tables (cell based table, state table). https://github.com/singularity-data/risingwave/pull/3214.
- [x] Implement dedup cell deserializer. https://github.com/singularity-data/risingwave/pull/3578
- [ ] Parameterize relational tables on RowSerde. 
- [ ] Test dedup cell ser/de interaction
- [ ] Deprecate cell based table iter. Replace with iter on `DedupPkCellBasedTable`. Related: [#3203](https://github.com/singularity-data/risingwave/issues/3203)
- [ ] Micro Benchmark of read-writes for relational layer. See `src/batch/benches/filter.rs`.
- [ ] E2e benchmark, use tpch. Take inspiration from row-based encoding benches.
- [ ] Implement dedup pk deserialization for lookup join state layer. Or entirely avoid dedup pk encoding for index. Update: There seems to be some work on using relational layer for lookup join. Perhaps we can support it now.
- [ ] Use dedup pk encoding for mview writes
- [ ] Benchmark (maybe separate into separate issue).

**Comment by kwannoel** [comment]
Closing this, no longer worked on.
