### ISSUE TITLE
Tracking: distinct aggregation

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#3589]
- [x] add expand operator #3563 
- [x] support selective aggregate #3506. We don't need provide this feature to user but use it interneally now.
  - [x] _(optional)parse and bind `FILTER(WHERE..)`_
  - [x] add `Condition` for `PlanAggCall`
  - [x] implement filter for batch agg.
  - [x] implement filter for streaming agg.
    - [x] #4179
- [x] add DistinctAgg rule for optimizer. IMO, there is no much difference between implementing it in planner and implemnting it as a rule, but a rule may provide more flexbility. #3717
