### ISSUE TITLE
[Tracking] streaming: async flush and operator merge support

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#39]
Currently, we can only get output of HashAgg after `flush` is called. That is because states like `Max` requires:

1. `apply_batch` generates a sequence of change log (flush_status)
2. merge the status to the state store by flushing them in write batch
3. read the real `max` from the state store

This will cause several problems:

* flushing a large incremental state will lead to spike latency
* in some of our fail-over designs, we can only add SST to the LSM tree when all nodes have processed the barrier

Therefore, managed states shouldn't require that all changes have been flushed before producing the correct output for this epoch.

To achieve this, we will need:

- [ ] implement iterator on StateStore
- [ ] implement state merge on `get_output` for ManagedExtremeState
- [ ] implement state merge on ManagedStringAggState
- [ ] ... when other ManagedStates are added, add new tasks here
- [ ] support async flush in HashAgg
- [ ] support async flush in SimpleAgg
- [ ] ... when other executors are integrated into the state store, add new tasks here
