### ISSUE TITLE
Tracking: enable more regress tests

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#4089]
Now we have enabled our regress test in CI. We are planning to enable more test cases.

PG has a lot of existing test cases. 
However:
1. We are not planning to support all of the features invoked in them.
2. It takes too much effort to be compatible with PG in terms of error messages.
3. We want to prioritize those SQLs that are more likely to be used by our users.

- [ ] advisory_lock.sql
- [ ] aggregates.sql
- [ ] alter_generic.sql
- [ ] alter_operator.sql
- [ ] alter_table.sql
- [ ] amutils.sql
- [ ] arrays.sql
- [ ] async.sql
- [ ] bit.sql
- [ ] bitmapops.sql
- [ ] boolean.sql
- [ ] box.sql
- [ ] brin.sql
- [ ] brin_bloom.sql
- [ ] brin_multi.sql
- [ ] btree_index.sql
- [ ] case.sql
- [ ] char.sql
- [ ] circle.sql
- [ ] cluster.sql
- [ ] collate.icu.utf8.sql
- [ ] collate.linux.utf8.sql
- [ ] collate.sql
- [ ] combocid.sql
- [ ] comments.sql
- [ ] compression.sql
- [ ] conversion.sql
- [ ] copy2.sql
- [ ] copydml.sql
- [ ] copyselect.sql
- [ ] create_aggregate.sql
- [ ] create_am.sql
- [ ] create_cast.sql
- [ ] create_function_3.sql
- [ ] create_index.sql
- [ ] create_index_spgist.sql
- [ ] create_misc.sql
- [ ] create_operator.sql
- [ ] create_procedure.sql
- [ ] create_table.sql
- [ ] create_table_like.sql
- [ ] create_type.sql
- [ ] create_view.sql
- [ ] date.sql
- [ ] dbsize.sql
- [ ] delete.sql
- [ ] dependency.sql
- [ ] domain.sql
- [ ] drop_if_exists.sql
- [ ] drop_operator.sql
- [ ] enum.sql
- [ ] equivclass.sql
- [ ] errors.sql
- [ ] event_trigger.sql
- [ ] explain.sql
- [ ] expressions.sql
- [ ] fast_default.sql
- [ ] float4.sql
- [ ] float8.sql
- [ ] foreign_data.sql
- [ ] foreign_key.sql
- [ ] functional_deps.sql
- [ ] generated.sql
- [ ] geometry.sql
- [ ] gin.sql
- [ ] gist.sql
- [ ] groupingsets.sql
- [ ] guc.sql
- [ ] hash_func.sql
- [ ] hash_index.sql
- [ ] hash_part.sql
- [ ] horology.sql
- [ ] hs_primary_extremes.sql
- [ ] hs_primary_setup.sql
- [ ] hs_standby_allowed.sql
- [ ] hs_standby_check.sql
- [ ] hs_standby_disallowed.sql
- [ ] hs_standby_functions.sql
- [ ] identity.sql
- [ ] incremental_sort.sql
- [ ] index_including.sql
- [ ] index_including_gist.sql
- [ ] indexing.sql
- [ ] indirect_toast.sql
- [ ] inet.sql
- [ ] infinite_recurse.sql
- [ ] inherit.sql
- [ ] init_privs.sql
- [ ] insert.sql
- [ ] insert_conflict.sql
- [ ] int2.sql
- [ ] int4.sql
- [ ] int8.sql
- [ ] interval.sql
- [ ] join.sql
- [ ] join_hash.sql
- [ ] json.sql
- [ ] json_encoding.sql
- [ ] jsonb.sql
- [ ] jsonb_jsonpath.sql
- [ ] jsonpath.sql
- [ ] jsonpath_encoding.sql
- [ ] limit.sql
- [ ] line.sql
- [ ] lock.sql
- [ ] lseg.sql
- [ ] macaddr.sql
- [ ] macaddr8.sql
- [ ] matview.sql
- [ ] misc_functions.sql
- [ ] misc_sanity.sql
- [ ] money.sql
- [ ] multirangetypes.sql
- [ ] mvcc.sql
- [ ] name.sql
- [ ] namespace.sql
- [ ] numeric.sql
- [ ] numeric_big.sql
- [ ] numerology.sql
- [ ] object_address.sql
- [ ] oid.sql
- [ ] oidjoins.sql
- [ ] opr_sanity.sql
- [ ] partition_aggregate.sql
- [ ] partition_info.sql
- [ ] partition_join.sql
- [ ] partition_prune.sql
- [ ] password.sql
- [ ] path.sql
- [ ] pg_lsn.sql
- [ ] plancache.sql
- [ ] plpgsql.sql
- [ ] point.sql
- [ ] polygon.sql
- [ ] polymorphism.sql
- [ ] portals.sql
- [ ] portals_p2.sql
- [ ] prepare.sql
- [ ] prepared_xacts.sql
- [ ] privileges.sql
- [ ] psql.sql
- [ ] psql_crosstab.sql
- [ ] publication.sql
- [ ] random.sql
- [ ] rangefuncs.sql
- [ ] rangetypes.sql
- [ ] regex.linux.utf8.sql
- [ ] regex.sql
- [ ] regproc.sql
- [ ] reindex_catalog.sql
- [ ] reloptions.sql
- [ ] replica_identity.sql
- [ ] resultcache.sql
- [ ] returning.sql
- [ ] roleattributes.sql
- [ ] rowsecurity.sql
- [ ] rowtypes.sql
- [ ] rules.sql
- [ ] sanity_check.sql
- [ ] select.sql
- [ ] select_distinct.sql
- [ ] select_distinct_on.sql
- [ ] select_having.sql
- [ ] select_implicit.sql
- [ ] select_into.sql
- [ ] select_parallel.sql
- [ ] select_views.sql
- [ ] sequence.sql
- [ ] spgist.sql
- [ ] stats.sql
- [ ] stats_ext.sql
- [ ] strings.sql
- [ ] subscription.sql
- [ ] subselect.sql
- [ ] sysviews.sql
- [ ] tablesample.sql
- [ ] temp.sql
- [ ] text.sql
- [ ] tid.sql
- [ ] tidrangescan.sql
- [ ] tidscan.sql
- [ ] time.sql
- [ ] timestamp.sql
- [ ] timestamptz.sql
- [ ] timetz.sql
- [ ] transactions.sql
- [ ] triggers.sql
- [ ] truncate.sql
- [ ] tsdicts.sql
- [ ] tsearch.sql
- [ ] tsrf.sql
- [ ] tstypes.sql
- [ ] tuplesort.sql
- [ ] txid.sql
- [ ] type_sanity.sql
- [ ] typed_table.sql
- [ ] unicode.sql
- [ ] union.sql
- [ ] updatable_views.sql
- [ ] update.sql
- [ ] uuid.sql
- [ ] vacuum.sql
- [ ] varchar.sql
- [ ] window.sql
- [ ] with.sql
- [ ] write_parallel.sql
- [ ] xid.sql
- [ ] xml.sql
- [ ] xmlmap.sql

Therefore, not all of the test cases need to be supported.

We may prioritize to support:
1. type that is frequently used, e.g. boolean.sql, etc
2. key functionalities, e.g. window.sql, etc
3. create, select, delete, drop.

**Comment by lmatz** [comment]
For bugs, unimplemented features that get discovered when enabling more test cases,

if it can be fixed/done quickly, please file an issue and fix it before enabling that test case.
if big, please file an issue and comment out those lines in the test case.

**Comment by lmatz** [comment]
As @neverchanje pointed out in #4093, we need a `rowsort`-like functionality in regress tests to make the test case aware/unaware of the order of results output by a `select` query, which means we need to interpret the output file instead of just comparing two big strings(the whole actual/expected output file).

The motivation is that Postgres and RisingWave output the results in different orders, this should be accepted as SQL without `order by` does not impose order on the result set.

It is doable, but
one question is: should we just move to `sqllogictest` now?
A blocker is that for those RisingWave-special session variables, we need to let the `sqllogictest` ignore them when we run test cases against PG.

**Comment by liurenjie1024** [comment]
> It is doable, but
one question is: should we just move to sqllogictest now?

Some test cases need to reference `data` directory to pre insert data. If we migrate to sqllogictest, we may need to extend sqllogictest to preload data.

Also the effort maybe huge since some test cases contains several thousands of  lines of code, which maybe difficult to review and maintain.

> A blocker is that for those RisingWave-special session variables, we need to let the sqllogictest ignore them when we run test cases against PG.

I think we can achieve this by using  `onlyif` directive?

**Comment by lmatz** [comment]
After #5428, we can start to enable:
int2
int4
int8
float4
float8
timestamptz
