### ISSUE TITLE
Tracking Issue: a more compact `Row`

### ISSUE THREAD

**Issue by yuhao-su** [singularity-data/risingwave#4166]
This issue tracks the development of a more compact `Row` to replace our current `Vec<Datum>`
https://singularity-data.quip.com/AxjfAoX7EfbU/New-In-Memory-Row-Format

- [ ] implement a new `RowV2` structure, test with ut.
- [ ] get `Datum`/`DatumRef` from `RowV2`.
- [ ] implement serializations
- [ ] replace rows in Risingwave (this step may have a lot of changes, can be done crate by crate)

Related issue
#3150

**Comment by BowenXiao1999** [comment]
If we got a binary-encoded `Row`, I think the extended query mode can have better performance: Do not need to serialize again for `BINARY` protocol mode. relate #4049

**Comment by yuhao-su** [comment]
Not needed for now.
