### ISSUE TITLE
Tracking: deterministic simulation testing

### ISSUE THREAD

**Issue by wangrunji0408** [singularity-data/risingwave#4180]
We are utilizing deterministic simulation testing to find bugs efficiently and reproduce them at any time.

## Status and TODO

- [x] Unit test
  - [ ] Find out why some tests failed
- [x] End-to-end test
  - [x] Batch and Streaming
  - [ ] Source and Sink
  - [ ] Parallel test
  - [ ] Cluster: 3 compute + 1 frontend
  - [ ] MinIO and etcd?
- [ ] Nexmark
- [ ] Make things deterministic
- [ ] Fault injection

## Pull Requests

- #2477
- #2718
- #2787
- #2888
- #3951
- #4176

**Comment by lmatz** [comment]
Is it possible to add e2e simulation tests for the connector sink or source?
e.g. https://github.com/risingwavelabs/risingwave/pull/6631

**Comment by wangrunji0408** [comment]
> Is it possible to add e2e simulation tests for the connector sink or source?
> e.g. #6631

Theoretically it's possible. But we have to build a dedicated simulator for each kind of source and sink. Each of them will take us at least 0.5 man-months in my prediction. Currently we already have a simulator for kafka. With this, the complete data flow from source to sink has been covered in the test. So any more simulator for a connector will only result in the connector code itself being tested, which I don't think the ROI is high. 🤔

By the way, I just found a new project [hermit](https://github.com/facebookexperimental/hermit) published by Meta a week ago. It is a system-level deterministic testing tool. It seems like a good solution to this case. I'm going to do some research on it soon.
