### ISSUE TITLE
Tracking: Functional Dependency

### ISSUE THREAD

**Issue by Enter-tainer** [singularity-data/risingwave#4357]
- Inference functional dependency for logical nodes
  - [x] strict functional dependency #4201 
  - [ ] lax functional dependency
- Optimization using functional dependency
  - [ ] remove unnecessary group key
  - [ ] remove redundant pk
  - [ ] ...
