### ISSUE TITLE
Tracking: ss-bench roadmap.

### ISSUE THREAD

**Issue by Sunt-ing** [singularity-data/risingwave#45]
Stage one:
- [x] A command line executable tool `ss_bench` with following capabilities:
	- Configurable backends: (`InMemoryStateStore`, hummock+s3, hummock+minio, `TikvStateStore`, `RocksDBStateStore`)
	- Configurable hummock options: (SST size, block size, bloom filter, default bucket, checksum algo, etc..)
	- Configurable data sizes: (key length/value length).
	- Configurable mode: (simple get/ simple scan / simple write_batch / mixed).

Stage two:
- [x] Launch Premetheus endpoint to expose internal storage counters.
- [x] Configurable concurrencies: (multithreaded `get`/`scan`/`write_batch` operations).

Stage three: more likely patterns as our internal states:
- [x] key_space number option.
- [x] (Sequential, random) x (read, writes, deletes, updates)
- [x] (Sequential, random ingestion) x (Tiered, Leveled compaction)
- [x] #1006

Detailed steps:
- [x] -seed (Seed base for random number generators. When 0 it is deterministic.)      type: int64 default: 0
- [x] ensure and doc each parameter types
- [x] Currently, the number of sequential read operations should be no larger than KV number of a single batch, because only one batch would be ingested. This is not cool.
- [x] Currently, operations of a --benchmarks are independent. Need to investigate how data reuse works between operations of a --benchmarks in db_bench.

-------------ss_bench refactor plan---------------

Design doc: https://singularity-data.quip.com/PzCPARd1jppE/ssbench-how-to-implement-streaming-workload-generator-for-ssbenchWIP

Related issue: #618
