### ISSUE TITLE
Tracking: refactor relational table

### ISSUE THREAD

**Issue by wcy-fdu** [singularity-data/risingwave#4557]
RFC: [New Design of Relational Table](https://singularity-data.quip.com/WyWoAAiAmjwB/RFC-New-Design-of-Relational-Table)

To refactor relational table as described, we should do:

- [x] refactor `StorageTable` to match row-based encoding
- [x] change `MemTable` to store Rows in `Vec<u8>`  and serialize Row before writing into `MemTable`
- [x] refactor `StateTableIter` into a merge iter of `MemTableIter` and `HummockIter`, remove `StorageTable` in streaming mode.
- [x] refactor `StorageTable<READ_ONLY>` in batch mode.

**Comment by wcy-fdu** [comment]
Completed.
