### ISSUE TITLE
Tracking: Shared Buffer Redesign

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#4754]
## Stage 1: Support basic functionalities before integration with executor
Interfaces:
- [ ] Actor: add control channel for streaming actor
- [ ] LocalStateStore: basic read/write/control interfaces definition
- [ ] WriteQueue: queue and queue item definition

Implementations:
- [ ] LocalStateStore: mutable/immutable memtable
- [ ] LocalStateStore: read interfaces (point get, iterator)
- [ ] LocalStateStore: write interfaces (single kv write, flush to write queue)
- [ ] LocalStateStore: control interfaces (version update, immutable memtable update)
- [ ] WriteQueue: queue consumer data structure
- [ ] WriteQueue: local compaction
- [ ] WriteQueue: sync interface and upload to s3
- [ ] Version: remote version observer and version delta propagation to LocalStateStore
- [ ] Version: remote version unpin
 

### Acceptance Criteria
- [ ] Observe improvements in micro-bench versus the current implementation

## Stage 2: Integrate with streaming executors
- [ ] Actor: handle control message from control channel
- [ ] StateStore: replace current StateStore in StateTable with LocalStateStore
- [ ] WriteQueue: send control message to actor control channel

### Acceptance Criteria
- [ ] Pass sequential and parallel e2e tests.
- [ ] Observe no performance regression in e2e bench versus the current implementation

## Stage 3: Support advanced functuinalities
- [ ] Queryable StateStore for batch query
- [ ] Spill to disk/s3
- [ ] Memtable flush ahead (before seeing a barrier)
- [ ] In-memory compaction without syncing to disk/s3
- [ ] Support lookup executor delta buffer for state sharing

### Acceptance Criteria
- [ ] Pass sequential and parallel e2e tests.
- [ ] Pass large state benchmark

***

Doc: https://singularity-data.quip.com/nFsqAzUKyKqh/RFC-Revisit-Storage-Shared-Buffer-Design

**Comment by hzxa21** [comment]
I will remove this tracking issue from the release and create separated issues for the in-progress advanced functionalities support.

**Comment by hzxa21** [comment]
All works are done and we have been running RisingWave with this new design for months. For further improvements, let's create new issues for tracking. Close this issue for now.
