### ISSUE TITLE
Tracking: Refactor column_id & column index

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#480]
[Design Doc](https://singularity-data.quip.com/ZgE7AG36CQZ0/Alter-Table-and-Column-ID)

- [x] #481
- [x] Refactor Table & Source Manager
- [x] #542 (the read path)
- [x] #534 (the write path)
- [ ] Refactor HashJoinExecutor
- [ ] Refactor HashAggExecutor

**Comment by xxchan** [comment]
Is this done?
