### ISSUE TITLE
Tracking Issue: Nested data support

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#515]
Parser: 
- [x] Support parsing ROW expression. `ROW(1.0, 2, "abc)` or (1.0, 2, "abc"), e.g.   https://github.com/singularity-data/risingwave-dev/pull/463
- [x] [Support parsing ARRAY expression.](https://github.com/singularity-data/risingwave-dev/issues/516)

Integration
- [x] Create a flatten table schema according to proto file. https://github.com/singularity-data/risingwave-legacy/pull/2747
- [x] #575
- [x] #582

Binder:
- [x] #581
- [x] Support binding values with LIST type when they are parsed as ARRAY.
- [x] Bind field selection, wildcard field selection and array access expression.

Execution:
- [x] Introduce STRUCT data type: https://github.com/singularity-data/risingwave-dev/pull/485
- [x] Introduce StructArray: https://github.com/singularity-data/risingwave-dev/pull/451 
- [x] #578
- [x] #579
- [x] #580
- [x] #583
- [x] #584

Pgwire
- [x] #576
- [x] #577

**Comment by xxchan** [comment]
finished?
