### ISSUE TITLE
Tracking: scale in Meta Service

### ISSUE THREAD

**Issue by yezizp2012** [singularity-data/risingwave#60]
This a tracking issues for scale ability in Meta Service, steps as follow:
- [ ] support frontend/backend evict/join in meta, all worker should have one state in Starting/Ready/Evicted.
- [x] support source/table/mview node init in new compute node.
- [ ] support actor reschedule in stream manager, including actor move/expanding/reduction.
- [ ] support fragment sharing in stream manager, including fragment search/match/config change etc.
- [ ] ...

**Comment by yezizp2012** [comment]
Replaced by #3750.
