### ISSUE TITLE
Tracking: shared state support in streaming engine

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#719]
https://singularity-data.quip.com/JXxMAhxzBKmD/Shared-State-Shared-Index-and-Efficient-Joins

- [x] Support remote write in Hummock https://github.com/singularity-data/risingwave-dev/pull/718
- [x] Lookup executor https://github.com/singularity-data/risingwave/pull/822
- [x] Arrange executor https://github.com/singularity-data/risingwave-dev/pull/775
- [x] meta rewrite https://github.com/singularity-data/risingwave/issues/1807
- [ ] frontend support https://github.com/singularity-data/risingwave/issues/885
- [ ] benchmark

Misc changes:

- [ ] https://github.com/singularity-data/risingwave/issues/1882
- [ ] https://github.com/singularity-data/risingwave/issues/1881
