### ISSUE TITLE
Tracking: Benckmarking RisingWave

### ISSUE THREAD

**Issue by zehaowei** [singularity-data/risingwave#94]
This is to track the works related to benckmarking state store of RisingWave. The final goal is to do the experiments in this doc: https://singularity-data.larksuite.com/docs/docusF6l8lV5BuOCWoq7Cu71fEe

Stage 1
- [x] Dimensions and metrics for state management of RisingWave
- [x] Experiments configuration
- [x] Implement state backends for RocksDB singularity-data/risingwave-legacy#2292
- [x] Implement state backends for TiKV singularity-data/risingwave-legacy#2202 
- [x] Implement `MetricsManager` for RisingWave singularity-data/risingwave-legacy#2198 singularity-data/risingwave-legacy#2234

Stage 2
- [x] singularity-data/risingwave-legacy#2285 singularity-data/risingwave-legacy#2359
- [x] singularity-data/risingwave-legacy#2410
- [x] singularity-data/risingwave-legacy#2436
- [x] #195
- [x] #194
- [x] singularity-data/risingwave-legacy#2411
- [x] singularity-data/risingwave-dev#45 (Implement ss_bench tool for state store layer)
- [x] singularity-data/risingwave-dev#127

Stage 3
- [x] Conduct StateStore benchmark using ss_bench on memory, RocksDB, TiKV and Hummock backends
- [ ] E2E Performance experiments(TPC-H)
- [ ] E2E Performance experiments(Nexmark)
- [ ] Overhead & cost experiments
