### ISSUE TITLE
Tracking: Frontend Catalog

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#959]
## MVP Features
* [x] singularity-data/risingwave-legacy#2261
* [x] singularity-data/risingwave-legacy#2572
* [x] singularity-data/risingwave-legacy#2669
* [ ] singularity-data/risingwave-legacy#2347
* [x] singularity-data/risingwave-legacy#2473
* [x] singularity-data/risingwave-dev#958

## Refactor
* [x] singularity-data/risingwave-legacy#2560
* [x] singularity-data/risingwave-dev#415
* [x] singularity-data/risingwave-legacy#2592
* [x] singularity-data/risingwave-legacy#2917

## Table V2
- [x] #1199
